---
title: "R Notebook"
output: html_notebook
---

## Goodreads_Books 
## Descriptive Statistics
## Haifaa Alzahrani
## 21/10/2020

### Theoretical Probability Distribution
It is empirical frequency distribution (on the sample = dataset),
which reflects the distributions of a variable that we observe in a given sample.

```{r}
# Overview 
summary(dataset)
```
Average rating distribution.
```{r}
ggplot(dataset,aes(x=average_rating)) +      
  geom_density(alpha= 0.5,fill='#8dd3c7')+ 
  geom_vline(aes(xintercept=mean(average_rating)), linetype='dashed')+
  geom_text(aes(x=4.1, y=.8, label='mean'), size=3)+
  ggtitle('Average Rating Destribution')
```
Ratings count distribution.
```{r}
dataset %>% 
  ggplot(aes(x=ratings_count)) + 
  geom_histogram(bins = 30, fill = "#3F3666")+ 
  ggtitle('Ratings Count Destribution')
```

Review count distribution
```{r}
dataset %>% 
  ggplot(aes(x= text_reviews_count)) + 
  geom_histogram(bins=30, fill = "#fdb462")+ 
  ggtitle('Review Count Destribution')
```

Page Number distribution
```{r}
dataset %>% 
  ggplot(aes(x=num_pages)) + 
  geom_histogram(bins = 30, fill = "#bebada")+ 
  ggtitle('Page Number Destribution')
```